apiVersion: v2
appVersion: "3.1.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.15.0
description: Midarr is a minimal lightweight media server for enjoying your media
home: https://truecharts.org/charts/incubator/midarr
icon: https://truecharts.org/img/hotlink-ok/chart-icons/midarr.png
keywords:
  - midarr
  - media
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: midarr
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/midarr
  - https://github.com/midarrlabs/midarr-server
version: 4.0.1
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
