apiVersion: v2
appVersion: "0.0.2"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.15.0
deprecated: false
description: The Wyoming integration of piper
home: https://truecharts.org/charts/incubator/wyoming-piper
icon: https://truecharts.org/img/hotlink-ok/chart-icons/wyoming-piper.png
keywords:
  - wyoming-piper
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: wyoming-piper
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/wyoming-piper
  - https://github.com/home-assistant/addons/tree/master/piper
type: application
version: 0.0.3
annotations:
  truecharts.org/catagories: |
    - home-automation
  truecharts.org/SCALE-support: "true"
