apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.15.0
deprecated: false
description: backup all your tasmota devices in one place.
home: https://truecharts.org/charts/incubator/tasmobackup
icon: https://truecharts.org/img/hotlink-ok/chart-icons/tasmobackup.png
keywords:
  - tasmobackup
  - HomeAutomation
  - Network-Management
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: tasmobackup
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/tasmobackup
  - https://github.com/danmed/TasmoBackupV1
type: application
version: 3.0.1
annotations:
  truecharts.org/catagories: |
    - HomeAutomation
    - Network-Management
  truecharts.org/SCALE-support: "true"
