apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: factorio
version: 4.0.7
appVersion: "stable"
description: "This Chart Chart will download the latest stable release of the game, generate the map and you're ready to play."
type: application
deprecated: false
home: https://truecharts.org/charts/incubator/factorio
icon: https://truecharts.org/img/hotlink-ok/chart-icons/factorio.png
keywords:
  - factorio
  - GameServers
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/factorio
  - https://www.factorio.com/
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.15.0
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - GameServers
  truecharts.org/SCALE-support: "true"
