apiVersion: v2
appVersion: "2.1.1"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.15.0
description: Dashy helps you organize your self-hosted services by making them accessible from a single place
home: https://truecharts.org/charts/incubator/dashy
icon: https://truecharts.org/img/hotlink-ok/chart-icons/dashy.png
keywords:
  - dashboard
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: dashy
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/dashy
  - https://github.com/airsonic/airsonic
version: 3.0.12
annotations:
  truecharts.org/catagories: |
    - dashboard
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
