image:
  repository: tccr.io/truecharts/kavita
  pullPolicy: IfNotPresent
  tag: v0.7.5@sha256:22136cb9604ce51252c458b1b8bef9f3c74892f5b6ee3bef96940d069b57dea1
service:
  main:
    ports:
      main:
        targetPort: 5000
        port: 10189
persistence:
  config:
    enabled: true
    mountPath: "/kavita/config"
  manga:
    enabled: true
    mountPath: "/manga"
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
