apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.15.0
description: A self-hosted internet performance tracking application that runs speedtest checks against Ookla's Speedtest service.
home: https://truecharts.org/charts/incubator/speedtest-tracker
icon: https://truecharts.org/img/hotlink-ok/chart-icons/speedtest-tracker.png
keywords:
  - speedtest
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: speedtest-tracker
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/speedtest-tracker
  - https://github.com/alexjustesen/speedtest-tracker
version: 4.0.16
annotations:
  truecharts.org/catagories: |
    - speedtest
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
