image:
  repository: tccr.io/truecharts/collabora
  pullPolicy: IfNotPresent
  tag: v23.05.1.3.1@sha256:b1dbcd6f551b75d6a2153ee5a24cfe5e9252e3b71dc629b1b74cb5e29cca97a8

collabora:
  username: admin
  password: changeme
  interface: default
  dictionaries:
    - de_DE
    - en_GB
    - en_US
    - el_GR
    - es_ES
    - fr_FR
    - pt_BR
    - pt_PT
    - it
    - nl
    - ru
  server_name: example.com
  aliasgroup1: https://cloud.example.com
  ssl_enable: false
  ssl_termination: true
  no_gen_ssl: true
  extra_params:
    - --o:welcome.enable=false

workload:
  main:
    podSpec:
      containers:
        main:
          envFrom:
            - configMapRef:
                name: collabora-config
          securityContext:
            runAsUser: 100
            runAsGroup: 102
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: true
            capabilities:
              add:
                - CHOWN
                - FOWNER
                - SYS_CHROOT
                - MKNOD

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9980
        port: 9980

portal:
  open:
    enabled: true
