apiVersion: v2
appVersion: "latest"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.15.0
deprecated: false
description: Self-hosted Rick Roll chart.
home: https://truecharts.org/charts/incubator/rickroll
icon: https://truecharts.org/img/hotlink-ok/chart-icons/rickroll.png
keywords:
  - rickroll
  - Other
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: rickroll
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/rickroll
  - https://github.com/modem7/docker-rickroll
type: application
version: 3.0.7
annotations:
  truecharts.org/catagories: |
    - Other
  truecharts.org/SCALE-support: "true"
