apiVersion: v2
appVersion: "0.7.30"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.15.0
deprecated: false
description: WireGuard-based VPN server and egress firewall
home: https://truecharts.org/charts/incubator/firezone
icon: https://truecharts.org/img/hotlink-ok/chart-icons/firezone.png
keywords:
  - firezone
  - wireguard
  - vpn
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: firezone
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/firezone
  - https://github.com/firezone/firezone
type: application
version: 0.0.5
annotations:
  truecharts.org/catagories: |
    - vpn
    - security
  truecharts.org/SCALE-support: "true"
