apiVersion: v2
appVersion: "3.4.4"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.15.0
deprecated: false
description: OpenHab is a home-automation application
home: https://truecharts.org/charts/stable/openhab
icon: https://truecharts.org/img/hotlink-ok/chart-icons/openhab.png
keywords:
  - openhab
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: openhab
sources:
  - https://github.com/truecharts/charts/tree/master/charts/stable/openhab
type: application
version: 5.0.18
annotations:
  truecharts.org/catagories: |
    - media
    - test
  truecharts.org/SCALE-support: "true"
