apiVersion: v2
appVersion: "1.19.0"
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 12.15.0
deprecated: false
description: Python script to update metadata and automatically build collections.
home: https://truecharts.org/charts/incubator/plex-meta-manager
icon: https://truecharts.org/img/hotlink-ok/chart-icons/plex-meta-manager.png
keywords:
  - plex-meta-manager
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
name: plex-meta-manager
sources:
  - https://github.com/truecharts/charts/tree/master/charts/incubator/plex-meta-manager
  - https://github.com/meisnate12/Plex-Meta-Manager
type: application
version: 3.0.1
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
